import './globals.css';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

import Logo from './components/Logo';
import NavBar from './components/NavBar';
import FilterMenu from './components/FilterMenu';

export const metadata = {
  title: 'Real Estate Rental',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='flex h-[10vh] items-center justify-center bg-black col-start-1 col-end-3 row-start-1 row-end-2'>
          <Logo />
          <NavBar />
        </header>
        <main className='flex w-screen min-h-[80%] col-start-1 col-end-3 row-start-2 row-end-3'>
          <FilterMenu />
          {children}
        </main>
        <footer className='flex h-[10vh] justify-center items-center bg-black py-4 col-start-1 col-end-3 row-start-3 row-end-4 '>
          Developed by Ricardo Pina
        </footer>
      </body>
    </html>
  );
}
